### ISSUE TITLE
sending messages to room

### ISSUE THREAD

**Issue by brunoqc** [matrix-org/go-neb#74]
Is there a way to send a message to a room with a POST request?

I would love to have the bot notify me when a command is done running on the server like this:

```sh
make ; curl --data "compilation is done!" ...
```

**Comment by ara4n** [comment]
go-neb itself doesn't do this, but there are other tools which can. 
curl itself can do it, but it's a bit ugly - the requests look like:

```
curl 
'https://matrix.org/_matrix/client/r0/rooms/!uYDPMSSXHjasdfdwq%3Amatrix.org/send/m.room.message/m1475011239679.575?access_token=secretsecretsecret' 
-X PUT --data '{"msgtype":"m.text","body":"compilation is done"}'
```

Alternatively, there's something like @rrix's mcat 
(http://fort.kickass.systems:10082/cgit/personal/rrix/pub/mcat.git, 
although the repo sadly seems to be down atm).

We're thinking of writing another official tool for injecting/retrieving 
data straight into Matrix from the commandline (which can also do E2E 
crypto), but haven't started yet.

**Comment by brunoqc** [comment]
I just wrote a tiny service for go-neb but I'm not sure if it should be included since it seems simple with curl directly.

What is `m1475011239679.575`?

**Comment by ara4n** [comment]
m1475011239679.575 is a transaction ID for this send operation.

**Comment by Kegsay** [comment]
> I just wrote a tiny service for go-neb but I'm not sure if it should be included since it seems simple with curl directly.

Yeah I'd rather not include this given it's basically a direct proxy of what Matrix natively supports. E.g. you can PUT a message into a room by talking to your Homeserver. This service would make Go-NEB accept POST requests and basically proxy it through directly and PUT to the Homeserver - it doesn't add anything new. 

> What is m1475011239679.575?

In order to ensure [idempotency](http://www.restapitutorial.com/lessons/idempotency.html), we encourage the use of `PUT` requests rather than `POST` requests. The "transaction ID" (in this case "m1475011239679.575" is an arbitrary value used to identify that message, so you can retry it again and again and not get duplicate messages. Most people end up using something like a unix timestamp as the transaction ID.
